### ISSUE TITLE
Cypress nightly builds on CircleCI are broken

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino_product#78]
The Cypress nightly builds on CircleCI are broken since 06.08.2022. The [last successful build was 2516](https://app.circleci.com/pipelines/github/Caleydo/ordino_product/1347/workflows/60864723-ab5c-4528-80ce-c1771a33aa09/jobs/2516). All following builds are broken and never got fixed.

I checked the CircleCI logs and saw that a different base image was used:

* [Build 2516](https://app.circleci.com/pipelines/github/Caleydo/ordino_product/1347/workflows/60864723-ab5c-4528-80ce-c1771a33aa09/jobs/2516): `cypress/base:10`
* Following builds (e.g., [2665](https://app.circleci.com/pipelines/github/Caleydo/ordino_product/1495/workflows/5e492381-c247-4f69-a37e-26648a21640c/jobs/2665)): `cimg/python:3.10.6-node`

Looking at the git history the Docker images for the CircleCI job has been changed to `executor: node-executor` which uses the CircleCI base image with PR https://github.com/Caleydo/ordino_product/pull/74/files.

Previously:

```yml
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
```

Now:

```yml
    executor: node-executor
    environment:
      CYPRESS_host: "https://ordino-daily.caleydoapp.org/"
```
